name: shell checks
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  shell-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run shfmt
        uses: reviewdog/action-shfmt@v1
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
